### ISSUE TITLE
Installing from pypi fails due to missing requirements.txt

### ISSUE THREAD

**Issue by asmundg** [dsoprea/PythonEtcdClient#1]
```
$ pip install etcd
Downloading/unpacking etcd
  Downloading etcd-2.0.8.tar.gz
  Running setup.py egg_info for package etcd
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/build/etcd/setup.py", line 13, in <module>
        with open(os.path.join(app_path, 'resources', 'requirements.txt')) as f:
    IOError: [Errno 2] No such file or directory: 'etcd/resources/requirements.txt'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/build/etcd/setup.py", line 13, in <module>

    with open(os.path.join(app_path, 'resources', 'requirements.txt')) as f:

IOError: [Errno 2] No such file or directory: 'etcd/resources/requirements.txt'

----------------------------------------
Command python setup.py egg_info failed with error code 1
```

**Comment by asmundg** [comment]
Local steps to reproduce:
1. python setup.py sdist
2. pip install dist/etcd-2.0.8.tar.gz

**Comment by kelbyers** [comment]
I have hit this same problem, trying to install using pip on a RHEL 6 box. However, I have been able to install it on another RHEL 6 system, and have installed it in several different virtualenvs on a Mac.

```
(os-stores)[jxb2016@cpliqa7b ~]$ pip install etcd
Downloading/unpacking etcd
  Downloading etcd-2.0.8.tar.gz
  Running setup.py egg_info for package etcd
Traceback (most recent call last):
  File "<string>", line 16, in <module>
  File "/home/jxb2016/os-stores/build/etcd/setup.py", line 13, in <module>
    with open(os.path.join(app_path, 'resources', 'requirements.txt')) as f:
IOError: [Errno 2] No such file or directory: 'etcd/resources/requirements.txt'
Complete output from command python setup.py egg_info:
Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/home/jxb2016/os-stores/build/etcd/setup.py", line 13, in <module>

with open(os.path.join(app_path, 'resources', 'requirements.txt')) as f:

IOError: [Errno 2] No such file or directory: 'etcd/resources/requirements.txt'
```

**Comment by dsoprea** [comment]
I'm not sure if I've ever seen this bug. Sorry for the delay.

**Comment by kelbyers** [comment]
The install works just fine when installing from source code, but I see the error when installing from pypi. It seems as if the tarball that gets downloaded from there is missing the requirements.txt file.

**Comment by jcdyer** [comment]
I'm still seeing this issue.  You may need to add a MANIFEST.in to your project, or set package_data in your setup.py

**Comment by ghost** [comment]
+1 so, it really doesn't "just work" :-P

**Comment by dhsh244** [comment]
Hi,

I am also running into the same issue and some additional observations from my side,

This issue has been there since "etcd==2.0.3"
So my immediate workaround is simply installing "etcd==2.0.2".

Any progress here would be much appreciated : )
