### ISSUE TITLE
ImportError: No module named simplejson

### ISSUE THREAD

**Issue by akuzminsky** [dsoprea/PythonEtcdClient#6]
```
$ python
Python 2.7.10 (default, May 25 2015, 13:06:17)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from etcd.client import Client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/etcd/client.py", line 13, in <module>
    from etcd.node_ops import NodeOps
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/etcd/node_ops.py", line 11, in <module>
    from etcd.response import ResponseV2
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/etcd/response.py", line 2, in <module>
    import simplejson
ImportError: No module named simplejson
```

**Comment by sanggi-wjg** [comment]
$ pip install simplejson

**Comment by dsoprea** [comment]
The project should be using the built-in _json_ package. This should've never been an issue. Feel free to submit a PR.
